### ISSUE TITLE
Don't access store directly

### ISSUE THREAD

**Issue by jimmyhmiller** [fusionalliance/autorenter-react#21]
Currently, we are access the store directly by passing it through router and yet we are still using `connect`. In the three locations where we are doing this, it isn't needed, connect is sufficient. It is also considered bad practice because it can lead to potential errors.

Three places:

[LoginContainer](https://github.com/fusionalliance/autorenter-react/blob/9a36050428bcfada80b8ab4cba437ee0c153ec5e/src/components/login/LoginContainer.js#L20)
[VehicleContainer](https://github.com/fusionalliance/autorenter-react/blob/9a36050428bcfada80b8ab4cba437ee0c153ec5e/src/components/fleet/VehicleContainer.js#L17)
[LocationContainer](https://github.com/fusionalliance/autorenter-react/blob/9a36050428bcfada80b8ab4cba437ee0c153ec5e/src/components/fleet/LocationContainer.js#L17)

Dan Abramov (creator of redux) recommending against it.
https://github.com/reactjs/react-redux/issues/108#issuecomment-182553478

**Comment by aamato1990** [comment]
👍
