### ISSUE TITLE
refactor locations & vehicles grid to be reusable

### ISSUE THREAD

**Issue by aamato1990** [fusionalliance/autorenter-react#23]
The grid (display component) should map over columns/data and be reusable in both the location and vehicles containers, as opposed to having essentially duplicate code for the grid component in each of the containers.

**Comment by camoore1979** [comment]
@BWortman I believe that this issue #23 and issue #25 are essentially the same thing. Let's close this one, and use #25 to do that work?

**Comment by BWortman** [comment]
Agreed.
