### ISSUE TITLE
Sortable tables

### ISSUE THREAD

**Issue by BernzSed** [fusionalliance/autorenter-react#25]
In the fleet tab, the locations table in LocationsList.js is sortable, but the vehicle table in VehicleList.js currently isn't. We should refactor much of the sort functionality out of LocationsList.js and reuse it in VehiclesList.js.

**Comment by camoore1979** [comment]
So I think the intent here is to:
- [ ] abstract the common parts of the Locations List and Vehicle List
- [ ] and make them both sortable
