### ISSUE TITLE
Vehicle/Location data not loaded for breacrumbs

### ISSUE THREAD

**Issue by BernzSed** [fusionalliance/autorenter-react#26]
When loading or refreshing a page with a vehicle or location, the breadcrumbs sometimes don't show the vehicle VIN or location name because that data has not been loaded.

FleetView.js uses data from the redux store to display vehicle VINs and location names in the breadcrumbs component, but this data might not be in the store if the page was just loaded or refreshed.

![screen shot 2017-10-11 at 2 12 08 pm](https://user-images.githubusercontent.com/203066/31458561-70c74fc0-ae8e-11e7-82d2-dd89288cd19a.png)

**Comment by ryanstrandt** [comment]
location view is fixed in #36

**Comment by BWortman** [comment]
Please let me close all Issues. Issues can't be closed until the associated PR is approved and merged.
