### ISSUE TITLE
As a User, I expect to be routed before/after logging in and out

### ISSUE THREAD

**Issue by camoore1979** [fusionalliance/autorenter-react#31]
As a User, I expect...
- [ ] if not yet authenticated, that app should route to /login page
- [ ] if logged in, app should route to main landing page
- [ ] if I log out, app should route to /login page

Per https://fusion-alliance.gitbooks.io/autorenter-spec/content/modules/main_module/main_interactions.html#login

**Comment by jcornfusionalliance** [comment]
@ryanstrandt 

Hey Dude, 

I messed up and did a pr on this one. 

I just saw it was yours. 

My bad man

**Comment by ryanstrandt** [comment]
I have not had time to pull the updates down and test again. Sorry.

**Comment by JakeTheCorn** [comment]
No big deal.  I just wanted to make sure I wasn't stepping on toes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JakeTheCorn** [comment]
This issue was resolved in PR #42
