### ISSUE TITLE
As a User, I expect to see the AutoRenter app title in the header.

### ISSUE THREAD

**Issue by camoore1979** [fusionalliance/autorenter-react#32]
- [x] "AutoRenter" should be in the header
- [x] clicking on App name should redirect to Landing Page

Per https://fusion-alliance.gitbooks.io/autorenter-spec/content/modules/main_module/main_interactions.html#landing

**Comment by camoore1979** [comment]
@BWortman this issue is resolved with PR https://github.com/fusionalliance/autorenter-react/pull/39. Should be able to close now.

**Comment by JakeTheCorn** [comment]
@camoore1979 

You cool if we close this one?

**Comment by camoore1979** [comment]
@JakeTheCorn normally @BWortman reserves the power to close actual issues. So let's see if he can close.

**Comment by JakeTheCorn** [comment]
Good deal man .  I'm taking a little break but I'll pick it up later

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JakeTheCorn** [comment]
@BWortman 

This can be closed.  It's completely fixed.
