### ISSUE TITLE
As I User, on the Tech Support page, I can fetch and view the API information.

### ISSUE THREAD

**Issue by camoore1979** [fusionalliance/autorenter-react#33]
- [x] Tech Support page fetches and display API information on load
- [x] 'Refresh' button will fetch and display the API information

Per https://fusion-alliance.gitbooks.io/autorenter-spec/content/modules/tech_support_module/tech_support_interactions.html

**Comment by camoore1979** [comment]
@JakeTheCorn I am actually working on this one, and it's about done.

**Comment by camoore1979** [comment]
@BWortman we should be able to close this issue.

**Comment by BWortman** [comment]
Yes, thanks @camoore1979
