### ISSUE TITLE
As a User, on the Tech Support page, I can raise an HTTP error 

### ISSUE THREAD

**Issue by camoore1979** [fusionalliance/autorenter-react#34]
- [ ] Clicking the 'HTTP Error' button will issue a GET /api/raise-error

Per https://fusion-alliance.gitbooks.io/autorenter-spec/content/modules/tech_support_module/tech_support_interactions.html

**Comment by camoore1979** [comment]
@JakeTheCorn I am actually working on this one as well.

**Comment by JakeTheCorn** [comment]
@camoore1979 

Cool man!

Thanks
