### ISSUE TITLE
Location Detail info pulling in and displaying

### ISSUE THREAD

**Issue by ryanstrandt** [fusionalliance/autorenter-react#35]
details for location are not displayed on location detail page.

**Comment by ryanstrandt** [comment]
merged into dev/rstrandt

**Comment by BWortman** [comment]
Please let me close all Issues.

**Comment by JakeTheCorn** [comment]
Hey @ryanstrandt, what is the status of this issue?

I know you're busy, so if you'd like I can pull it down and work on it. 

Thanks man!

**Comment by camoore1979** [comment]
@BWortman I believe that this bug has been fixed, this issue can be closed now.
